version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
configuration:
  templates:
    - name: python3-fastapi
      source: https://github.com/loudsquelch/openfaas-python3-fastapi-template
